name: 中青助力分享阅读

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-21/3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/a33032480/rZools.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【youthshare】'
        run: |
          cd ~/js   
          node ./youthshare.js
