name: youth_gain2(中青浏览赚)

on:
  workflow_dispatch:
  schedule:
     - cron: '08 1,6,22 * * *'
  watch:
    types: youth_gain
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_START21: ${{ secrets.YOUTH_START21 }}
      YOUTH_LOOK21: ${{ secrets.YOUTH_LOOK21 }}
      YOUTH_START22: ${{ secrets.YOUTH_START22 }}
      YOUTH_LOOK22: ${{ secrets.YOUTH_LOOK22 }}
      YOUTH_START23: ${{ secrets.YOUTH_START23 }}
      YOUTH_LOOK23: ${{ secrets.YOUTH_LOOK23 }}
      YOUTH_START24: ${{ secrets.YOUTH_START24 }}
      YOUTH_LOOK24: ${{ secrets.YOUTH_LOOK24 }}
      YOUTH_START25: ${{ secrets.YOUTH_START25 }}
      YOUTH_LOOK25: ${{ secrets.YOUTH_LOOK25 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【账号一中青浏览赚】'
        if: env.YOUTH_START21
        run: |
          node youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START21 }}
          YOUTH_LOOK: ${{ secrets.YOUTH_LOOK21 }}
       
      - name: '运行 【账号二中青浏览赚】'
        if: env.YOUTH_START22
        run: |
          node youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START22 }}
          YOUTH_LOOK: ${{ secrets.YOUTH_LOOK22 }}
      - name: '运行 【账号三中青浏览赚】'
        if: env.YOUTH_START23
        run: |
          node youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START23 }}
          YOUTH_LOOK: ${{ secrets.YOUTH_LOOK23 }}
      - name: '运行 【账号四中青浏览赚】'
        if: env.YOUTH_START24
        run: |
          node youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START24 }}
          YOUTH_LOOK: ${{ secrets.YOUTH_LOOK24 }}
      - name: '运行 【账号五中青浏览赚】'
        if: env.YOUTH_START25
        run: |
          node youth_gain.js
        env:
          YOUTH_START: ${{ secrets.YOUTH_START25 }}
          YOUTH_LOOK: ${{ secrets.YOUTH_LOOK25 }}

